default:
  image: "rust:latest"
  before_script:
    - echo "Start execution of before_script"
    - rustup self update
    - rustup update stable

stages:
  - test
  - deploy

variables:
  CARGO_REGISTRY_TOKEN: $CARTIS_API_KEY

test-job:
  stage: test
  script:
    - echo "Start execution of test-job"
    - cargo check
    - cargo test
    - cargo publish --dry-run
  allow_failure: false

deploy-job:
  stage: deploy
  needs:
    - test-job
  script:
    - echo "Start execution of deploy-job"
    - cargo build --release
    - cargo publish --token $CARGO_REGISTRY_TOKEN
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: always
