default:
  image: "rust:latest"

  before_script:
    - echo "Start execution of before_script"
    - rustup self update
    - rustup update stable
    - rustc --version
    - cargo --version

stages:
  - test
  - build

variables:
  CARGO_REGISTRY_TOKEN: $CARTIS_API_KEY

test-job:
  stage: test
  script:
    - echo "Start execution of test-job"
    - cargo check
    - cargo test
  allow_failure: false

build-job:
  stage: build
  script:
    - echo "Start execution of build-job"
    - cargo build --release
    - cargo publish --token $CARGO_REGISTRY_TOKEN
  needs:
    - test-job

  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: always