# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[package]
name = "rust_unique_pass"
version = "0.7.4"
edition = "2021"
license = "Apache-2.0"
description = "A CLI tool for generating strong password."
authors = ["Neuron Grid <neuron-grid@neuron-grid.net>"]
documentation = "https://docs.rs/crate/rust_unique_pass/latest"
repository = "https://gitlab.com/Neuron-Grid/rust_unique_pass"
readme = "README/README_eng.md"
keywords = ["passwords", "generate", "rupass", "cli", "commandline"]
categories = ["command-line-utilities"]

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
fluent = "0.16.1"
rand = "0.8.5"
rust-embed = { version = "8.4.0", features = ["include-exclude"] }
unic-langid = "0.9.5"
zxcvbn = "2.2.2"

[[bin]]
name = "rupass"
path = "src/main.rs"