# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[package]
name = "rust_unique_pass"
version = "0.6.1"
edition = "2021"
license = "Apache-2.0"
description = "A library for generating unique passwords in Rust"
readme = "./README/README_eng.adoc"

[dependencies]
clap = { version = "4.4.6", features = ["derive"] }
fluent = "0.16.0"
rand = "0.8.5"
rust-embed = { version = "8.0.0", features = ["include-exclude"] }
unic-langid = "0.9.1"
zxcvbn = "2.2.2"

[[bin]]
name = "rupass"
path = "src/main.rs"