= Rust Unique Pass

== feature
This software is designed to generate random strong passwords.
[%hardbreaks]
Users can customize the length of their passwords and the special characters they use.
[%hardbreaks]
Except for the FTL files for translation, everything is written in the Rust language.

== How to use
See *execution method* in the next section.
The command name is `rupass`.

=== How to force termination
- **For macOS**: `control` + `c`
- **For Windows**: `Ctrl` + `c`

[Warning]
====
Default language is English.
====

==  execution method
Please make sure that the `Rust language` is installed beforehand.
If not, please install it from the link:https://www.rust-lang.org/[official website].
If it has already been installed, move it to any folder and then execute the following command.

[source,zsh]
----
git clone https://github.com/Neuron-Grid/rust_unique_pass && \
cd rust_unique_pass && \
cargo build --release && \
cd /target/release/ && \
./rupass
----

== About Language Settings
*Languages supported*::
Japanese language:::
English language:::
German language:::

[%hardbreaks]
For use in languages other than English, specify the language code defined in `ISO 639-3`.
The command can be used in Japanese by making the following changes.
[source,zsh]
```
./rupass -l jpn
```

== This software utilizes the following crates
GitHub repository
[%hardbreaks]
- link:https://github.com/clap-rs/clap[clap]
- link:https://github.com/projectfluent/fluent-rs[fluent-rs]
- link:https://github.com/rust-random/rand[rand]
- link:https://github.com/pyrosseh/rust-embed[rust-embed]
- link:https://github.com/zbraniecki/unic-locale[unic-locale]
- link:https://github.com/shssoichiro/zxcvbn-rs[zxcvbn-rs]

== License
This software is released under the `Apache License 2.0`.
See link:../LICENSE[LICENSE] for details.

[%hardbreaks]
Copyright © 2023 Neuron Grid. 
Licensed under the link:https://www.apache.org/licenses/LICENSE-2.0[Apache License 2.0].
